### ISSUE TITLE
lwjgl?

### ISSUE THREAD

**Issue by zty012** [ReplayMod/jGui#9]
In many classes, 
Can't find package or class de.johni0702.minecraft.gui.utils.lwjgl

**Comment by Johni0702** [comment]
That dependency should be pulled in via JitPack. They do sometimes have outage issues, so if you're lucky (or well, were unlucky) it was just one of those outages and just refreshing gets it working.
If not, check if you can build via Gradle. If you can, then it's probably an issue with whatever IDE you're using.
